plugins {
    id 'com.android.application'
}

android {
    namespace 'com.system.phantom'
    compileSdk 34

    defaultConfig {
        applicationId "com.system.phantom"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // Bersih tanpa library luar untuk menghindari eror kompilasi
}
